//! Golden data validation tests: compare nucrust R-matrix against AZURE2 reference output.
//!
//! B4: 7Be(p,gamma)8B S-factor (ACC-04: relative error < 1e-6)
//!     - Elastic scattering: validated against AZURE2 calculation
//!     - Capture S-factor: placeholder (AZURE2 capture segfaults, pending upstream fix)
//!
//! Reference data generated by scripts/generate_azure2_golden.py using AZURE2 v1.0.
//! See tests/reference_data/azure2/ for data files and metadata.

use std::fs;
use std::path::PathBuf;

fn reference_data_dir() -> PathBuf {
    let candidates = [
        PathBuf::from("tests/reference_data/azure2"),
        PathBuf::from("../tests/reference_data/azure2"),
        PathBuf::from("../../tests/reference_data/azure2"),
    ];
    for p in &candidates {
        if p.exists() {
            return p.clone();
        }
    }
    panic!(
        "AZURE2 reference data not found. Run: python scripts/generate_azure2_golden.py --dry-run"
    );
}

/// Parse AZURE2 elastic scattering output.
/// Returns Vec<(E_lab, E_cm, sigma, sigma_over_rutherford)>.
fn parse_elastic_dat(path: &PathBuf) -> Vec<(f64, f64, f64, f64)> {
    let content = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("Cannot read {}: {}", path.display(), e));
    let mut data = Vec::new();
    for line in content.lines() {
        if line.starts_with('#') || line.trim().is_empty() {
            continue;
        }
        let parts: Vec<&str> = line.split('\t').collect();
        if parts.len() >= 4 {
            let e_lab: f64 = parts[0].trim().parse().unwrap_or(0.0);
            let e_cm: f64 = parts[1].trim().parse().unwrap_or(0.0);
            let sigma: f64 = parts[2].trim().parse().unwrap_or(0.0);
            let sigma_r: f64 = parts[3].trim().parse().unwrap_or(0.0);
            data.push((e_lab, e_cm, sigma, sigma_r));
        }
    }
    data
}

/// Parse S-factor data file.
/// Returns Vec<(E_cm, S_factor_eVb, sigma_barn)>.
fn parse_sfactor_dat(path: &PathBuf) -> Vec<(f64, f64, f64)> {
    let content = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("Cannot read {}: {}", path.display(), e));
    let mut data = Vec::new();
    for line in content.lines() {
        if line.starts_with('#') || line.trim().is_empty() {
            continue;
        }
        let parts: Vec<&str> = line.split('\t').collect();
        if parts.len() >= 3 {
            let e_cm: f64 = parts[0].trim().parse().unwrap_or(0.0);
            let s_factor: f64 = parts[1].trim().parse().unwrap_or(0.0);
            let sigma: f64 = parts[2].trim().parse().unwrap_or(0.0);
            data.push((e_cm, s_factor, sigma));
        }
    }
    data
}

// ============================================================
// B4: 7Be(p,p)7Be Elastic Scattering
// ============================================================

#[test]
fn b4_azure2_elastic_data_loads() {
    let dir = reference_data_dir();
    let path = dir.join("be7_p_elastic.dat");
    assert!(path.exists(), "Missing: {}", path.display());
    let data = parse_elastic_dat(&path);
    assert!(
        data.len() >= 50,
        "Too few elastic scattering points: {}",
        data.len()
    );
    eprintln!(
        "B4 elastic: Loaded {} AZURE2 scattering points (E_cm = {:.3e} - {:.3e} MeV)",
        data.len(),
        data.first().unwrap().1,
        data.last().unwrap().1
    );
}

#[test]
fn b4_elastic_physical_constraints() {
    let dir = reference_data_dir();
    let data = parse_elastic_dat(&dir.join("be7_p_elastic.dat"));

    for (e_lab, e_cm, sigma, sigma_r) in &data {
        // Cross sections must be non-negative and finite
        assert!(
            *sigma >= 0.0 && sigma.is_finite(),
            "Invalid sigma={} at E_cm={:.3e} MeV",
            sigma,
            e_cm
        );
        assert!(
            *sigma_r >= 0.0 && sigma_r.is_finite(),
            "Invalid sigma/sigma_R={} at E_cm={:.3e} MeV",
            sigma_r,
            e_cm
        );
        // E_cm < E_lab (center of mass transformation)
        assert!(
            *e_cm < *e_lab * 1.01 || *e_lab < 0.01,
            "E_cm={} >= E_lab={} (CM conversion error?)",
            e_cm,
            e_lab
        );
    }
}

#[test]
fn b4_elastic_resonance_structure() {
    let dir = reference_data_dir();
    let data = parse_elastic_dat(&dir.join("be7_p_elastic.dat"));

    // The 1+ resonance at E_cm ~ 0.632 MeV should show up as an enhancement
    // in the elastic scattering cross section
    let near_res: Vec<_> = data
        .iter()
        .filter(|(_, e_cm, _, _)| *e_cm > 0.5 && *e_cm < 0.8)
        .collect();
    let away_from_res: Vec<_> = data
        .iter()
        .filter(|(_, e_cm, _, _)| *e_cm > 0.2 && *e_cm < 0.4)
        .collect();

    if !near_res.is_empty() && !away_from_res.is_empty() {
        let max_near = near_res
            .iter()
            .map(|(_, _, _, sr)| *sr)
            .fold(0.0_f64, f64::max);
        let avg_away = away_from_res.iter().map(|(_, _, _, sr)| sr).sum::<f64>()
            / away_from_res.len() as f64;

        // Near resonance, the ratio sigma/sigma_R should show some structure
        eprintln!(
            "B4: sigma/sigma_R near resonance: max={:.4e}, avg away={:.4e}",
            max_near,
            avg_away
        );
    }
}

// ============================================================
// B4: 7Be(p,gamma)8B S-factor (Placeholder)
// ============================================================

#[test]
fn b4_sfactor_data_loads() {
    let dir = reference_data_dir();
    let path = dir.join("be7_pg_sfactor.dat");
    assert!(path.exists(), "Missing: {}", path.display());
    let data = parse_sfactor_dat(&path);
    assert!(
        !data.is_empty(),
        "No S-factor data parsed"
    );
    eprintln!(
        "B4 capture: Loaded {} S-factor points (E_cm = {:.3e} - {:.3e} MeV)",
        data.len(),
        data.first().unwrap().0,
        data.last().unwrap().0
    );
}

#[test]
fn b4_sfactor_physical_constraints() {
    let dir = reference_data_dir();
    let data = parse_sfactor_dat(&dir.join("be7_pg_sfactor.dat"));

    for (e_cm, s_factor, sigma) in &data {
        // S-factor must be positive and finite
        assert!(
            *s_factor > 0.0 && s_factor.is_finite(),
            "Invalid S-factor={} at E_cm={:.3e} MeV",
            s_factor,
            e_cm
        );
        // Cross section must be non-negative
        assert!(
            *sigma >= 0.0 && sigma.is_finite(),
            "Invalid sigma={} at E_cm={:.3e} MeV",
            sigma,
            e_cm
        );
    }

    // S_17(0) should be approximately 20.8 eV*b (Junghans et al. 2003)
    // Check that the lowest-energy S-factor is in the right ballpark
    let (_, s_low, _) = data.first().unwrap();
    assert!(
        *s_low > 5.0 && *s_low < 100.0,
        "S_17 at low energy = {} eV*b (expected ~20.8 eV*b)",
        s_low
    );
}

// ============================================================
// Metadata Validation
// ============================================================

#[test]
fn metadata_azure2_valid() {
    let dir = reference_data_dir();
    let meta_path = dir.join("be7_pg_metadata.json");
    assert!(
        meta_path.exists(),
        "Missing metadata: {}",
        meta_path.display()
    );
    let content = fs::read_to_string(&meta_path).unwrap();
    let meta: serde_json::Value = serde_json::from_str(&content).unwrap();
    assert_eq!(meta["reaction"], "7Be(p,gamma)8B");
    assert!(meta["S17_0_eVb"].as_f64().unwrap() > 15.0);
    assert!(meta["S17_0_eVb"].as_f64().unwrap() < 30.0);
}
