[package]
name = "nucrust-data"
description = "RIPL-3 and REACLIB data parsers for nucrust"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
nucrust-core = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
faer = { workspace = true }

[dev-dependencies]
approx = { workspace = true }

[dependencies.hdf5]
package = "hdf5-metno"
version = "0.12"
optional = true

[features]
default = []
hdf5_io = ["hdf5"]
