//! ACC-01 validation: compare Coulomb wave functions against mpmath 50-digit reference.
//!
//! Reference data generated by scripts/generate_mpmath_reference.py (dps=60).
//! Required precision (SRS): relative error < 1e-12 for F and G.

use nucrust_special::coulomb_wave;
use serde::Deserialize;
use std::fs;

#[derive(Deserialize)]
struct ReferenceFile {
    data: ReferenceData,
}

#[derive(Deserialize)]
struct ReferenceData {
    tier1: Vec<ReferencePoint>,
    tier2: Vec<ReferencePoint>,
    tier3: Vec<ReferencePoint>,
    tier4_extreme: Vec<ReferencePoint>,
    recurrence: Vec<ReferencePoint>,
    nuclear_physics: Vec<ReferencePoint>,
    forbidden_region: Vec<ReferencePoint>,
    small_rho: Vec<ReferencePoint>,
    attractive: Vec<ReferencePoint>,
}

#[derive(Deserialize)]
struct ReferencePoint {
    l: u32,
    eta: f64,
    rho: f64,
    label: String,
    #[serde(rename = "F")]
    f_val: Option<f64>,
    #[serde(rename = "G")]
    g_val: Option<f64>,
    // The reference F'/G' are evaluated at full precision from the exact
    // relation X'_l = S_{l+1} X_l - R_{l+1} X_{l+1} (not by finite differences).
    #[serde(rename = "Fp")]
    fp_val: Option<f64>,
    #[serde(rename = "Gp")]
    gp_val: Option<f64>,
    // sigma/wronskian are present in the reference JSON but not compared here.
    #[allow(dead_code)]
    sigma: Option<f64>,
    #[allow(dead_code)]
    wronskian: Option<f64>,
    error: Option<String>,
}

fn relative_error(computed: f64, reference: f64) -> f64 {
    if reference.abs() < 1e-300 {
        computed.abs()
    } else {
        ((computed - reference) / reference).abs()
    }
}

/// Load reference data from the workspace root.
fn load_reference() -> ReferenceFile {
    // Try multiple paths to find the reference file
    let paths = [
        "../../tests/reference_data/coulomb_mpmath.json",
        "../../../tests/reference_data/coulomb_mpmath.json",
        "tests/reference_data/coulomb_mpmath.json",
    ];

    for path in &paths {
        if let Ok(content) = fs::read_to_string(path) {
            return serde_json::from_str(&content)
                .unwrap_or_else(|e| panic!("Failed to parse {path}: {e}"));
        }
    }

    panic!(
        "Could not find coulomb_mpmath.json. Run: cd scripts && uv run generate_mpmath_reference.py"
    );
}

/// Relative-error tolerances for one group of reference points.
struct Tolerances {
    /// F and G.
    fg: f64,
    /// F' and G'.
    deriv: f64,
    /// |F'G - FG' - 1| of the computed values.
    wronskian: f64,
}

// Tolerances are the measured maxima over all groups (F/G 6.3e-14, F'/G' 1.3e-13,
// |W-1| 7.8e-15) rounded up to the next power of ten. All are within the
// 1e-12 SRS target. Values are compared with their signs.
const TOL: Tolerances = Tolerances {
    fg: 1e-13,
    deriv: 1e-12,
    wronskian: 1e-14,
};

fn validate_point(point: &ReferencePoint, tol: &Tolerances, tier: &str) {
    assert!(
        point.error.is_none(),
        "[{tier}] reference point has generation error: {:?} [{}]",
        point.error,
        point.label
    );

    let result = coulomb_wave(point.eta, point.rho, point.l, 1).unwrap_or_else(|e| {
        panic!(
            "[{}] coulomb_wave({}, {}, l={}) failed: {} ({})",
            tier, point.eta, point.rho, point.l, e, point.label
        )
    });

    let checks = [
        ("F", result.f[0], point.f_val.unwrap(), tol.fg),
        ("G", result.g[0], point.g_val.unwrap(), tol.fg),
        ("F'", result.fp[0], point.fp_val.unwrap(), tol.deriv),
        ("G'", result.gp[0], point.gp_val.unwrap(), tol.deriv),
    ];
    for (name, computed, reference, tol) in checks {
        let err = relative_error(computed, reference);
        assert!(
            err < tol,
            "[{tier}] {name}_{}({}, {}): rel_err = {:.2e} > {:.0e} (computed={}, ref={}) [{}]",
            point.l,
            point.eta,
            point.rho,
            err,
            tol,
            computed,
            reference,
            point.label
        );
    }

    let w = result.fp[0] * result.g[0] - result.f[0] * result.gp[0];
    let w_err = (w - 1.0).abs();
    assert!(
        w_err < tol.wronskian,
        "[{tier}] Wronskian at l={}: |W-1| = {:.2e} > {:.0e} [{}]",
        point.l,
        w_err,
        tol.wronskian,
        point.label
    );
}

fn validate_tier(points: &[ReferencePoint], tier: &str) {
    assert!(
        !points.is_empty(),
        "{tier} reference data is empty; regenerate coulomb_mpmath.json"
    );
    for point in points {
        validate_point(point, &TOL, tier);
    }
}

#[test]
fn acc01_tier1_standard_cases() {
    validate_tier(&load_reference().data.tier1, "tier1");
}

#[test]
fn acc01_tier2_barrier_penetration() {
    validate_tier(&load_reference().data.tier2, "tier2");
}

#[test]
fn acc01_tier3_high_l() {
    validate_tier(&load_reference().data.tier3, "tier3");
}

#[test]
fn acc01_tier4_extreme_parameters() {
    validate_tier(&load_reference().data.tier4_extreme, "tier4_extreme");
}

#[test]
fn acc01_recurrence_consistency() {
    validate_tier(&load_reference().data.recurrence, "recurrence");
}

#[test]
fn acc01_nuclear_physics_cases() {
    validate_tier(&load_reference().data.nuclear_physics, "nuclear_physics");
}

#[test]
fn acc01_forbidden_region() {
    // l > 0 deep in the classically forbidden region, points on both sides of
    // the turning point, and large eta where neither the 1F1 series nor
    // Steed's method alone is accurate.
    validate_tier(&load_reference().data.forbidden_region, "forbidden_region");
}

#[test]
fn acc01_small_rho() {
    validate_tier(&load_reference().data.small_rho, "small_rho");
}

#[test]
fn acc01_attractive_coulomb() {
    validate_tier(&load_reference().data.attractive, "attractive");
}

#[test]
fn acc01_multi_l_matches_single_l() {
    // A multi-l call must reproduce the single-l results (same normalization
    // at l = 0, recurrences in l), including deep in the forbidden region.
    let reference = load_reference();
    for point in reference
        .data
        .forbidden_region
        .iter()
        .chain(&reference.data.tier3)
    {
        let single = coulomb_wave(point.eta, point.rho, point.l, 1).unwrap();
        let multi = coulomb_wave(point.eta, point.rho, 0, point.l + 3).unwrap();
        let i = point.l as usize;
        for (name, a, b) in [
            ("F", multi.f[i], single.f[0]),
            ("G", multi.g[i], single.g[0]),
        ] {
            let err = relative_error(a, b);
            assert!(
                err < TOL.fg,
                "{name}_{} multi-l vs single-l: rel_err = {err:.2e} [{}]",
                point.l,
                point.label
            );
        }
    }
}

#[test]
fn acc01_cross_product_identity_mpmath() {
    // F_{l-1} * G_l - F_l * G_{l-1} = l / sqrt(l^2 + eta^2)
    let reference = load_reference();

    // Use the recurrence points (l=0,1,2,3 at eta=2, rho=5)
    let points: Vec<_> = reference
        .data
        .recurrence
        .iter()
        .filter(|p| p.error.is_none())
        .collect();

    for i in 1..points.len() {
        let p_prev = &points[i - 1];
        let p_curr = &points[i];
        if p_prev.l + 1 != p_curr.l || p_prev.eta != p_curr.eta || p_prev.rho != p_curr.rho {
            continue;
        }

        let l = p_curr.l as f64;
        let eta = p_curr.eta;
        let cross = p_prev.f_val.unwrap() * p_curr.g_val.unwrap()
            - p_curr.f_val.unwrap() * p_prev.g_val.unwrap();
        let expected = l / (l * l + eta * eta).sqrt();

        let err = relative_error(cross, expected);
        assert!(
            err < 1e-10,
            "Cross product at l={}: rel_err = {:.2e}",
            p_curr.l,
            err
        );
    }
}
